name: Test
on:
  workflow_dispatch:

jobs:
  test_deno:
    name: Test with Deno
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: deno test
        run: deno test
