name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_deno:
    name: Test with Deno
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: type check source files
        run: deno task check
      - name: lint source files
        run: deno lint
      - name: lint documentation
        run: deno task doc:lint
      - name: test module
        run: deno test
